modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/firstdarkdev/pocketmachines"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://pocketmachines.fdd-docs.com"
logoFile="assets/pocketmachines/icon.png"
#credits=""
authors="${mod_author}"
description='''Simple, portable vanilla machines'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.0.0-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1)"
ordering="NONE"
side="BOTH"
