#Project
version_major=1
version_minor=0
version_patch=4
version_build=1
project_group=com.hypherionmc.pocketmachines
release_type=port

#Mod
mod_author=HypherionSA
mod_id=pocketmachines
mod_name=Simple Pocket Machines

# Shared
minecraft_version=1.21.9

# Fabric
fabric_loader=0.16.13
fabric_api=0.133.14+1.21.9

# NeoForge
neoforge_version=0-beta

# Gradle Options
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false